// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.Collections.Generic;

namespace TPFinalProgIII.Models
{
    public partial class Cliente
    {
        public Cliente()
        {
            Venta = new HashSet<Venta>();
        }

        public int IdCliente { get; set; }
        public long? IdCuitDni { get; set; }

        public virtual Persona IdCuitDniNavigation { get; set; }
        public virtual ICollection<Venta> Venta { get; set; }
    }
}