// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPFinalProgIII.Models
{
    public partial class DatosEnvioVenta
    {
        public DatosEnvioVenta()
        {
            EnvioVenta = new HashSet<EnvioVenta>();
        }

        public int IdDatosEnvioVenta { get; set; }
        public string NombreCompleto { get; set; }
        public string Provincia { get; set; }
        public string Ciudad { get; set; }
        public string Calle { get; set; }
        public int? Numero { get; set; }
        public string Aclaraciones { get; set; }

        public virtual ICollection<EnvioVenta> EnvioVenta { get; set; }
    }
}