// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.Collections.Generic;

namespace TPFinalProgIII.Models
{
    public partial class DetalleVenta
    {
        public DetalleVenta()
        {
            EnvioVenta = new HashSet<EnvioVenta>();
        }

        public int IdDetalleVenta { get; set; }
        public int? IdVenta { get; set; }
        public int? IdProducto { get; set; }
        public double? Precio { get; set; }
        public int? Cantidad { get; set; }
        public double? Descuento { get; set; }
        public double? Recargo { get; set; }

        public virtual Producto IdProductoNavigation { get; set; }
        public virtual Venta IdVentaNavigation { get; set; }
        public virtual ICollection<EnvioVenta> EnvioVenta { get; set; }
    }
}