// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.Collections.Generic;

namespace TPFinalProgIII.Models
{
    public partial class DetalleCompra
    {
        public DetalleCompra()
        {
            EnvioCompra = new HashSet<EnvioCompra>();
        }

        public int IdDetalleCompra { get; set; }
        public int? IdCompra { get; set; }
        public int? IdProducto { get; set; }
        public double? Precio { get; set; }
        public int? Cantidad { get; set; }
        public double? Retencion { get; set; }

        public virtual Compra IdCompraNavigation { get; set; }
        public virtual Producto IdProductoNavigation { get; set; }
        public virtual ICollection<EnvioCompra> EnvioCompra { get; set; }
    }
}