// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace TPFinalProgIII.Models
{
    public partial class EnvioVenta
    {
        public long IdCodigoSeguimiento { get; set; }
        public int? IdDetalleVenta { get; set; }
        public int? IdDireccion { get; set; }
        public string Correo { get; set; }
        public string Sucursal { get; set; }

        public virtual DetalleVenta IdDetalleVentaNavigation { get; set; }
        public virtual Direccion IdDireccionNavigation { get; set; }
    }
}