// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPFinalProgIII.Models
{
    public partial class EnvioCompra
    {
        public long IdCodigoSeguimiento { get; set; }
        public int? IdDetalleCompra { get; set; }
        public string Correo { get; set; }
        public string Sucursal { get; set; }

        public virtual DetalleCompra IdDetalleCompraNavigation { get; set; }
    }
}